Vagrant.configure("2") do |config|
  config.vm.define "webservers" do |m1|
    m1.vm.box = "sbeliakou/centos"
    m1.vm.network :private_network, ip: "1.2.3.4"
    m1.vm.hostname = "webserver"
    m1.ssh.insert_key = false
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "webserver"
      vb.memory = "4096"
      end
  end
  config.vm.define "appserver" do |m2|
    m2.vm.box = "sbeliakou/centos"
    m2.vm.network :private_network, ip: "1.2.3.5"
    m2.vm.hostname = "appserver"
    m2.ssh.insert_key = false
    m2.vm.provider "virtualbox" do |vm|
      vm.name = "appserver"
      vm.memory = "4096"
      end
  end
end

