- name: Start Playbook
  hosts: all

  pre_tasks:
  - name: Creating Facts Directory
    become: yes
    file:
      path: /etc/ansible/facts.d
      recurse: yes
      state: directory

  roles: 
  - role: user
    user_name: devops
    user_priv: " {{user_name}}  ALL=(ALL)  NOPASSWD: ALL \n Defaults:{{ user_name }} !requiretty \n"
    user_auth_key: 
    - "/home/student/ansible/day1/devops.pub"
    - "/home/student/.ssh/id_rsa.pub"
