- hosts: localhost


  tasks:
  - name: Start Docker Container
    docker_container:
      name: "centos-{{ item }}"
      state: started
      image: sbeliakou/ansible-training:centos
      privileged: true
    with_sequence: count=3
    register: centos

  - name: Compose In-Memory Inventory
    add_host:
      name: "{{ container.NetworkSettings.IPAddress }}"
      ansible_host: "{{ container.Name }}"
      ansible_connection: docker
      groups:
      - loadbalancer
    loop: "[{{ centos.results[0] }}]"
    loop_control:
      label: "{{ container.Name }}"
    vars:
      container: "{{ item.ansible_facts.docker_container }}"

  - name: Compose In-Memory Inventory
    add_host:
      name: "{{ container.NetworkSettings.IPAddress }}"
      ansible_host: "{{ container.Name }}"
      ansible_connection: docker
      groups:
      - backends
    loop: "{{ centos.results[1:] }}"
    loop_control:
      label: "{{ container.Name }}"
    vars:
      container: "{{ item.ansible_facts.docker_container }}"

  - debug: var=groups

  - name: Compose In-Memory Inventory
    add_host:
      name: "{{ container.NetworkSettings.IPAddress }}"
      ansible_host: "{{ container.Name }}"
      ansible_connection: docker
      groups:
      - backends
    loop: "{{ centos.results[1:] }}"
    loop_control:
      label: "{{ container.Name }}"
    vars:
      container: "{{ item.ansible_facts.docker_container }}"

  - name: remove container
    docker_container:
      name: "{{hostvars[item].ansible_host}}"
      state: absent
    with_items: "{{ groups['loadbalancer'] + groups['backends']}}"

    

