apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-cli-deployment
  labels:
    app: docker-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-cli
  template:
    metadata:
      labels:
        app: docker-cli
    spec:
      containers:
      - name: docker-cli
        image: docker_cli
        securityContext:
          privileged: true
        ports:
        - containerPort: 4444
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket-volume
      volumes:
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock


---

apiVersion: v1
kind: Service
metadata:
  name: docker-cli-svc
  labels:
    app: docker-cli
spec:
  ports:
  - port: 80
    targetPort: 4444
  selector:
    app: docker-cli
  type: LoadBalancer




