Vagrant.configure("2") do |config|
config.vm.define "web" do |web|
  web.vm.box = "sbeliakou/centos"
  web.vm.hostname = "web"	 
  web.vm.network "private_network", ip: "192.168.133.100"
  web.vm.network "private_network", type: "dhcp"
  web.vm.provider "virtualbox" do |vb|
	vb.name = "Vagrant-VB-Web"     
	vb.memory = "1024"
  	end

  web.vm.provision "shell", inline: <<-SHELL
  yum update
  yum -y install httpd
  cp /vagrant/Vhost.conf /etc/httpd/conf.d/
  systemctl enable httpd
  systemctl start httpd
  SHELL
  end
(1..2).each do |i|
config.vm.define "tomcat #{i}" do |tomcat|
  tomcat.vm.box = "sbeliakou/centos"
  tomcat.vm.hostname = "tomcat-#{i}"
  tomcat.vm.network "private_network", ip: "192.168.133.10#{i}"
  tomcat.vm.network "private_network", type: "dhcp"
  tomcat.vm.provider "virtualbox" do |vb|
        vb.name = "Vagrant-VB-Tomcat-#{i}"
        vb.memory = "2048"
  	end
  tomcat.vm.provision "shell", inline: <<-SHELL
       	yum -y install tomcat
	cp /vagrant/clusterjsp.war /usr/share/tomcat/webapps
        systemctl enable tomcat
        systemctl start tomcat
	
        SHELL
	end
  end
end
