apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["/bin/sh", "-c", "echo 'Andrey Pavarnitsyn' > /usr/share/nginx/html/index.html; nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80

