Vagrant.configure("2") do |config|
config.vm.define "web" do |web|
  web.vm.box = "sbeliakou/centos"
  web.vm.hostname = "web"	 
  web.vm.network "private_network", ip: "192.168.133.100"
  web.vm.provider "virtualbox" do |vb|
	vb.name = "Web"     
	vb.memory = "2048"
  	end

#  web.vm.provision "shell", path: "provision.sh"
#  web.vm.provision "shell", path: "config.sh"
end
end
