Vagrant.configure("2") do |config|
  config.vm.box = "apavarnitsyn-vagrant-centos-7.6-x86_64-minimal.box"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network :private_network, ip: "5.12.19.89"
  config.vm.hostname = "localhost"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "localhost"
    vb.memory = "4096"
  end

end
