Vagrant.configure("2") do |config|
config.vm.define "web" do |web|
  web.vm.box = "sbeliakou/centos"
  web.vm.hostname = "web"	 
  web.vm.network "private_network", ip: "192.168.133.100"
  web.vm.provider "virtualbox" do |vb|
	vb.name = "Vagrant-VB-Web"     
	vb.memory = "4096"
  	end

  web.vm.provision "shell", inline: <<-SHELL
  yum update
  yum -y install nginx
  sed -e '/[::]:80/s/^/#/' -i /etc/nginx/nginx.conf
  systemctl enable nginx --now
  
  yum -y install tomcat
  systemctl enable tomcat --now
  rpm -ivh https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
  yum install -y zabbix-agent
sed -e '/Server=127.0.0.1/s/^/#/' -i /etc/zabbix/zabbix_agentd.conf
cat << EOF >> /etc/zabbix/zabbix_agentd.conf 
DebugLevel=3
Server=192.168.133.101
ListenPort=10050
ListenIP=0.0.0.0
StartAgents=3
EOF
  systemctl start zabbix-agent

  SHELL
  end

config.vm.define "zabbix" do |zabbix|
  zabbix.vm.box = "sbeliakou/centos"
  zabbix.vm.hostname = "web"
  zabbix.vm.network "private_network", ip: "192.168.133.101"
  zabbix.vm.provider "virtualbox" do |vb|
        vb.name = "Vagrant-VB-Zabbix"
        vb.memory = "4096"
        end

  zabbix.vm.provision "shell", inline: <<-SHELL 
	yum install -y mariadb-server
	/usr/bin/mysql_install_db --user=mysql
	systemctl start mariadb
	mysql -uroot -e "create database zabbix character set utf8 collate utf8_bin; grant all privileges on zabbix.* to zabbix@localhost identified by 'password';"
yum install https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
yum install -y zabbix-server-mysql zabbix-web-mysql
zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -ppassword zabbix 
cat << EOF >> /etc/zabbix/zabbix_server.conf 
DBPassword=password
DBHost=localhost
EOF
systemctl start zabbix-server
cat << EOF >> /etc/httpd/conf.d/zabbix.conf
php_value date.timezone Europe/Minsk
EOF
systemctl start httpd

        SHELL
  end
end

