Vagrant.configure("2") do |config|
(1..2).each do |i|
  config.vm.define "slave#{i}" do |m2|
    m2.vm.box = "sbeliakou/centos"
    m2.vm.network :private_network, ip: "1.2.3.4#{i}"
    m2.vm.hostname = "slave#{i}"
    m2.vm.provider "virtualbox" do |vb|
      vb.name = "slave#{i}"
      vb.memory = "2048"
      end
    m2.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
  end
end
end
end
