- hosts: localhost
  tasks:
  - name: Start Docker Container
    docker_container:
      name: "centos-{{ item }}"
      state: started
      image: sbeliakou/ansible-training:centos
      privileged: true
    with_sequence: count=2
    register: centos
    tags:
    - always
    - destroy


  - name: Compose In-Memory Inventory
    add_host:
      name: "{{ item.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
      ansible_host: "{{ item.ansible_facts.docker_container.Name }}"
      ansible_connection: docker
      groups: >-
        {% if item == centos.results[0] %} 
        webservers
        {% else %} 
        appservers
        {% endif %}
    loop: "{{ centos.results }}"
    loop_control:
      label: "{{ item.ansible_facts.docker_container.Name }}"
    tags:
    - always
    - destroy

  - debug: var=groups
