Vagrant.configure("2") do |config|
  config.vm.define "tomcat" do |m1|
    m1.vm.box = "sbeliakou/centos"
    m1.vm.network :private_network, ip: "1.2.3.4"
    m1.vm.hostname = "tomcat"
    m1.ssh.insert_key = false
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "tomcat"
      vb.memory = "4096"
      end
    m1.vm.provision "shell", path: "tomcat.sh"
  end
  config.vm.define "elastic" do |m2|
    m2.vm.box = "sbeliakou/centos"
    m2.vm.network :private_network, ip: "1.2.3.5"
    m2.vm.hostname = "elastic"
    m2.ssh.insert_key = false
    m2.vm.provider "virtualbox" do |vm|
      vm.name = "elastic"
      vm.memory = "4096"
      end
    m2.vm.provision "shell", path: "elastic.sh"
  end
end

